-- Data Tablespace
CREATE TABLESPACE storm_data
DATAFILE 'C:\APP\SAM\PRODUCT\21C\ORADATA\XE\storm_data01.dbf'
SIZE 500M
AUTOEXTEND ON NEXT 100M MAXSIZE 5G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

-- Index Tablespace
CREATE TABLESPACE storm_index
DATAFILE 'C:\APP\SAM\PRODUCT\21C\ORADATA\XE\storm_index01.dbf'
SIZE 300M
AUTOEXTEND ON NEXT 100M MAXSIZE 3G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

-- Temporary Tablespace
CREATE TEMPORARY TABLESPACE storm_temp
TEMPFILE 'C:\APP\SAM\PRODUCT\21C\ORADATA\XE\storm_temp01.dbf'
SIZE 300M
AUTOEXTEND ON NEXT 100M MAXSIZE 3G
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

-- SET DEFAULT TABLESPACES
ALTER USER nsh123
DEFAULT TABLESPACE storm_data
TEMPORARY TABLESPACE storm_temp;

-- move existing TABLES
ALTER TABLE zone MOVE TABLESPACE storm_data;
ALTER TABLE aircraft MOVE TABLESPACE storm_data;
ALTER TABLE sensors MOVE TABLESPACE storm_data;
ALTER TABLE sensor_data MOVE TABLESPACE storm_data;
ALTER TABLE threat_log MOVE TABLESPACE storm_data;
ALTER TABLE alerts MOVE TABLESPACE storm_data;
ALTER TABLE public_alerts MOVE TABLESPACE storm_data;
ALTER TABLE operators MOVE TABLESPACE storm_data;
ALTER TABLE system_logs MOVE TABLESPACE storm_data;

-- REBUILD INDEXES in tablespace storm_index
ALTER INDEX idx_sensor_data_latlon
REBUILD TABLESPACE storm_index;

ALTER INDEX idx_threat_detection_time
REBUILD TABLESPACE storm_index;

-- CHECK FOR PRIMARY KEY indexes (auto-generated)
SELECT index_name
FROM user_indexes
WHERE index_type = 'NORMAL'
AND generated = 'Y';

-- move them to their respective tablespace
ALTER INDEX SYS_C008225 REBUILD TABLESPACE storm_index;
ALTER INDEX SYS_C008227 REBUILD TABLESPACE storm_index;
ALTER INDEX SYS_C008228 REBUILD TABLESPACE storm_index;
ALTER INDEX SYS_C008230 REBUILD TABLESPACE storm_index;
ALTER INDEX SYS_C008234 REBUILD TABLESPACE storm_index;
ALTER INDEX SYS_C008239 REBUILD TABLESPACE storm_index;
ALTER INDEX SYS_C008242 REBUILD TABLESPACE storm_index;
ALTER INDEX SYS_C008244 REBUILD TABLESPACE storm_index;
ALTER INDEX SYS_C008245 REBUILD TABLESPACE storm_index;
ALTER INDEX SYS_C008260 REBUILD TABLESPACE storm_index;

-- VERIFY THAT TABLES AND INDEXES WERE MOVED
SELECT table_name, tablespace_name
FROM user_tables
ORDER BY table_name;
 
SELECT index_name, tablespace_name, status
FROM user_indexes
ORDER BY index_name;

-- VERIFY TEMP tablespace
SELECT tablespace_name, contents
FROM dba_tablespaces
WHERE tablespace_name = 'STORM_TEMP';








